# Generated by Django 3.2.5 on 2023-03-23 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=50, verbose_name='username')),
                ('password', models.CharField(default='', max_length=128, verbose_name='password')),
                ('name', models.CharField(default='', max_length=50, verbose_name='name')),
                ('sex', models.CharField(choices=[('male', 'male'), ('female', 'female')], default='', max_length=8, verbose_name='sex')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'user',
                'db_table': 'users',
            },
        ),
    ]
